(ns bewl.monoid.biker)

; Models the bicyclic monoid B in software, and its "omega" object O.
; B is generated by p and q with pq=1.
; The elements of B take the form (q ^ m) (p ^ n) represented by [m n].
; The elements of O are the right ideals (q ^ m)B represented by m,
; together with the empty right ideal which we ignore here.

(def bike-1 [0 0])

(defn bike-mul
  [[k l] [m n]]
  (if (< l m)
    [(+ k (- m l)) n]
    [k (+ (- l m) n)]
))

(defn bike-o-mul
  [k [m n]]
  (if (>= m k) 0
    (+ n (- k m))
))

